CREATE TABLE Employee 
(
	employeeID BIGINT NOT NULL UNSIGNED AUTO_INCREMENT,
	taxBracket DECIMAL(3,2) NOT NULL,
	nameFirst VARCHAR(20) NOT NULL,
	nameLast VARCHAR(20) NOT NULL,
	hoursWorked SMALLINT NOT NULL UNSIGNED,
	hourlyWage SMALLINT NOT NULL UNSIGNED,
	phoneNumber CHAR(12),
	address VARCHAR(255) NOT NULL,
    CHECK (taxBracket in (0.10,0.12,0.22,0.24,0.32,0.35,0.37)),
	PRIMARY KEY (employeeID)
);